<?php require 'templates/header.phtml' ?>




<?php foreach($albums as $album): ?>
<div class="albums-list">
    <ul class="album-list">
            <li><a href="album/<?= $album->id?>" type="button" class=''><?= $album->nombre?></a></li>
            <li><a href="album/<?= $album->id?>" type="button" class=''><?= $album->autor?></a></li>
            <li><a href="album/<?= $album->id?>" type="button" class=''><?=$album->fecha?></a></li>
            <?php if (isset($_SESSION['USER_ID'])) : ?>
                <li><a href="deleteAlbum/<?= $album->id ?>" type="button" >Borrar</a></li>
    </ul>
<?php endif ?>
</div>

<?php endforeach ?>


<?php if (isset($_SESSION['USER_ID'])) : ?>
    <div class="form-albums">

<?php require_once 'templates/formalbums.phtml' ?>

<form action="updateAlbum" method="POST">
            <h2>Modificar Album</h2>
            <label>Seleccione un Album</label>
            <select required name="id" class="">
                    <?php foreach($albums as $album): ?>
                    <option value="<?= $album->id?>"><?=$album->nombre ?></option>
                    <?php endforeach ?>
            </select>

            <div class="">
                <label>Nuevo nombre</label>
                <input name="nombre" type="text" class="">
            </div>

            <div class="">
                <label>Nuevo autor</label>
                <input name="autor" type="text" class="">
            </div>
            <div class="">
                <label>Nueva fecha</label>
                <input name="fecha" type="number" class="" min="1"> 
            </div>

    <button type="submit" class="">Guardar</button>
</form>

</div>


<?php endif ?>

<?php require 'templates/footer.phtml' ?>
