<?php require_once 'templates/header.phtml' ?>

<?php foreach($canciones as $cancion): ?>
    <ul class="album-list">
        <li><?= $cancion->nombre?></li>
        <li><?= $cancion->duracion?></li>
        <li><?=$cancion->album_nombre?></li>
        <?php if (isset($_SESSION['USER_ID'])) : ?>
            <li><a href="deleteCancion/<?= $cancion->id?>" type="button">Borrar</a></li>
        <?php endif ?>
    </ul>
<?php endforeach ?>

<?php if (isset($_SESSION['USER_ID'])) : ?>
    <div class="form-albums">
        <?php require_once 'templates/formCanciones.phtml' ?>
        <form action="editCancion" method="POST">
                    <label>Seleccione una Cancion</label>
                    <select required name="id" class="">
                            <?php foreach($canciones as $cancion): ?>
                            <option value="<?= $cancion->id?>"><?=$cancion->nombre ?></option>
                            <?php endforeach ?>
                    </select>

                    <div class="">
                        <label>Nuevo nombre</label>
                        <input name="nombre" type="text" class="">
                    </div>

                    <div class="">
                        <label>Nueva duracion</label>
                        <input name="autor" type="text" class="">
                    </div>
                    <div class="">
                        <label>Nuevo album</label>
                        <input name="fecha" type="number" class=""> 
                    </div>

            <button type="submit" class="">Guardar</button>
        </form>
    </div>

<?php endif ?>

<?php require_once 'templates/footer.phtml' ?>
