<!-- aca iria el template header -->

<ul class="list-group">
<?php foreach($canciones as $cancion): ?>
    <div>
        <a href="cancion/<?= $cancion->id?>" type="button">
            <li><?= $cancion->Nombre?></li>
            <li><?= $cancion->Duracion?></li>
            <li><?=$cancion->Album_fk?></li>
        </a>
    </div>
    <div>
        <a href="deleteCancion/<?= $cancion->id?>" type="button">Borrar</a>
    </div>
<?php endforeach ?>
</ul>

<?php require_once 'templates/formCanciones.phtml' ?>

<form action="editCancion" method="POST">
            <label>Seleccione una Cancion</label>
            <select required name="id" class="">
                    <?php foreach($canciones as $cancion): ?>
                    <option value="<?= $cancion->id?>"><?=$cancion->nombre ?></option>
                    <?php endforeach ?>
            </select>

            <div class="">
                <label>Nuevo nombre</label>
                <input name="nombre" type="text" class="">
            </div>

            <div class="">
                <label>Nueva duracion</label>
                <input name="autor" type="text" class="">
            </div>
            <div class="">
                <label>Nuevo album</label>
                <input name="fecha" type="number" class=""> 
            </div>

    <button type="submit" class="">Guardar</button>
</form>
<!-- aca iria el template footer -->
