<?php require_once 'templates/header.phtml' ?>

<ul class="albums-list">
<?php foreach($canciones as $cancion): ?>
    <div class='album-list'>
        <li><a href="cancion/<?= $cancion->id?>" type="button" class=''><?= $cancion->Nombre?></a></li>
        <li><a href="cancion/<?= $cancion->id?>" type="button" class=''><?= $cancion->Duracion?></a></li>
        <li><a href="cancion/<?= $cancion->id?>" type="button" class=''><?=$cancion->album_nombre?></a></li>
        <?php if (isset($_SESSION['USER_ID'])) : ?>
            <li><a href="deleteCancion/<?= $cancion->id?>" type="button" >Borrar</a></li>
            <?php endif ?>
    </div>
            <?php endforeach ?>
</ul>

<?php if (isset($_SESSION['USER_ID'])) : ?>
    <div class="form-albums">
        <?php require_once 'templates/formCanciones.phtml' ?>

<form action="editCancion" method="POST">
            <label>Seleccione una Cancion</label>
            <select required name="id" class="">
                    <?php foreach($canciones as $cancion): ?>
                    <option value="<?= $cancion->id?>"><?=$cancion->Nombre ?></option>
                    <?php endforeach ?>
            </select>

                    <div class="">
                        <label>Nuevo nombre</label>
                        <input name="nombre" type="text" class="">
                    </div>
                    <div class="">
                        <label>Nueva duracion</label>
                        <input name="duracion" type="text" class="">
                    </div>
                    <div class="">
                        <label>Nuevo album</label>
                        <select required name="album" class="">
                            <?php foreach($albums as $album): ?>
                            <option value="<?= $album->id?>"><?=$album->nombre ?></option>
                            <?php endforeach ?>
                        </select> 
                    </div>

            <button type="submit" class="">Guardar</button>
        </form>
    </div>

<?php endif ?>

<?php require_once 'templates/footer.phtml' ?>
