<form action="addCancion" method="POST">
            <div class="">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="">
            </div>

            <div class="">
                <label>Duracion</label>
                <input required name="duracion" type="text" class="">
            </div>
            <div class="">
                <label>Album</label>
                <input required name="album" type="text" class=""> 
            </div>

    <button type="submit" class="">Guardar</button>
</form>