<form action="addAlbum" method="POST">
            <div class="">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="">
            </div>

            <div class="">
                <label>Autor</label>
                <input required name="autor" type="text" class="">
            </div>
            <div class="">
                <label>Fecha</label>
                <input required name="fecha" type="number" class="" min="1"> 
            </div>

    <button type="submit" class="">Guardar</button>
</form>

