<form action="addCancion" method="POST">
    <h2>Añadir cancion</h2>
            <div class="">
                <label>Nombre</label>
                <input required name="nombre" type="text" class="">
            </div>

            <div class="">
                <label>Duracion</label>
                <input required name="duracion" type="text" class="">
            </div>
            <div class="">
                <label>Album</label>
                <select required name="Album_fk" class="">
                    <?php foreach($albums as $album): ?>
                    <option value="<?= $album->id?>"><?=$album->nombre ?></option>
                    <?php endforeach ?>
            </select>
            </div>

    <button type="submit" class="">Guardar</button>
</form>