<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <base href="<?= BASE_URL ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="./styles/estilos.css">
    
    <title>Cancionero</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="nav-link" href="albums">Albums</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
        <li class="nav-item active">
            <a class="nav-link" href="canciones">Canciones</a>
        </li>


        <?php if (!isset($_SESSION['USER_ID'])) : ?>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="login">Login</a>
            </li>
        <?php else : ?>
            <li class="nav-item">
                <a class="nav-link" aria-current="page" href="logout">Logout (<?= $_SESSION['USER_NAME'] ?>)</a>
            </li>
        <?php endif ?>
        </ul>
    </div>
    </nav>
